version: '3.1'

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - "5431:5432"

  backend:
    build: .
    ports:
      - "8080:8080"
    restart:
      always
    volumes:
      - ./app:/app
    depends_on:
      - db
    working_dir: /app
    entrypoint: python server.py